web/src/main/resources/security/authorities-default.yaml
Jag har gjort en ny feature-branch i refdata också, men är lite osäker på hur vi ska hantera dem. Det är något jag tar med Peter efter påsk.
https://inera-certificate.atlassian.net/browse/INTYG-8347
=> INTYG-8347: Tandläkare ska kunna utfärda AF00213

build.gradle
Godkänn följande två PR först:
- https://github.com/sklintyg/common/pull/6
- https://github.com/sklintyg/infra/pull/2
=> INTYGFV-10875: Ny schemas-contract med trådsäker hashning

web/src/main/webapp/app/mixins/_wc-variables.scss, web/src/main/webapp/app/views/index/index.scss, web/src/main/webapp/app/views/index/wcFooter/wcFooter.directive.scss
Passade även på att bli av med sidoscroll vid liten skärmbredd.
=> INTYGFV-11512: Fixat placeringen av footern

devops/openshift/INSTALL.md
Räcker med denna rubrik under **Installation Checklist** eller ska jag lägga till en punkt i **Installation Checklist**? Det är ändå något som kan ändras mellan två releaser. Jag har påbörjat en intern wiki-sida också med mer intern information.
=> INTYGFV-11719: INSTALL dokumentation - Logstash filters

web/src/main/java/se/inera/intyg/webcert/web/service/monitoring/MonitoringLogService.java, web/src/main/java/se/inera/intyg/webcert/web/service/monitoring/MonitoringLogServiceImpl.java, web/src/main/java/se/inera/intyg/webcert/web/web/controller/api/JsLogApiController.java, web/src/main/java/se/inera/intyg/webcert/web/web/controller/api/dto/MonitoringRequest.java
Stöd för backendloggning vid misslyckad NetID signering
=> INTYGFV-11695: Added signing improvements and backend-logging

Jenkinsfile, web/src/main/java/se/inera/intyg/webcert/web/service/monitoring/HealthMonitor.java
Även bumpat patch version och städat upp lite kod samt felhantering.
=> INTYGFV-11852: Redis-skript för att räkna sessioner har tagits bort.

Jenkinsfile, web/src/main/java/se/inera/intyg/webcert/web/service/monitoring/HealthMonitor.java, web/src/main/resources/default.properties
Av någon anledning saknades konfiguration för att kunna deploya webcert i demo.
=> Saknades konfig variable

build.gradle, notification-sender/src/main/java/se/inera/intyg/webcert/notification_sender/notifications/routes/NotificationRouteHeaders.java, notification-sender/src/main/java/se/inera/intyg/webcert/notification_sender/notifications/services/v3/NotificationWSClient.java, notification-sender/src/test/java/se/inera/intyg/webcert/notification_sender/mocks/NotificationStubEntry.java, notification-sender/src/test/java/se/inera/intyg/webcert/notification_sender/mocks/v3/CertificateStatusUpdateForCareResponderStub.java, notification-sender/src/test/java/se/inera/intyg/webcert/notification_sender/notifications/integration/AbstractBaseIT.java, notification-sender/src/test/java/se/inera/intyg/webcert/notification_sender/notifications/integration/RouteIT.java, notification-sender/src/test/java/se/inera/intyg/webcert/notification_sender/notifications/services/v3/NotificationWSClientTest.java, stubs/notification-stub/src/main/java/se/inera/intyg/webcert/notificationstub/NotificationStubRestApi.java, stubs/notification-stub/src/main/java/se/inera/intyg/webcert/notificationstub/v3/CertificateStatusUpdateForCareResponderStub.java, test/webcertTestTools/package-lock.json, test/webcertTestTools/package.json, test/webcertTestTools/pages/intyg/ag/ag7804/ag7804.intyg.page.js, test/webcertTestTools/pages/intyg/base.intyg.page.js, test/webcertTestTools/pages/intyg/fk/smi/smi.base.intyg.page.js, web/package-lock.json, web/package.json, web/src/main/java/se/inera/intyg/webcert/web/service/notification/NotificationServiceImpl.java, web/src/main/resources/ui.properties, web/src/main/webapp/app/views/index/wcFooter/loginMetoderElegHelp.html, web/src/main/webapp/app/views/index/wcFooter/wcFooter.directive.html
Reverts sklintyg/webcert#75
Feature branch var inte i synk med develop och uppdaterade en hel del filer...
=> Revert "feature/INTYGFV-10829: Skicka med "hanteradAv" med statusuppdateringar (notifieringar)."

build.gradle, notification-sender/src/main/java/se/inera/intyg/webcert/notification_sender/notifications/routes/NotificationRouteHeaders.java, notification-sender/src/main/java/se/inera/intyg/webcert/notification_sender/notifications/services/v3/NotificationWSClient.java, notification-sender/src/test/java/se/inera/intyg/webcert/notification_sender/mocks/NotificationStubEntry.java, notification-sender/src/test/java/se/inera/intyg/webcert/notification_sender/mocks/v3/CertificateStatusUpdateForCareResponderStub.java, notification-sender/src/test/java/se/inera/intyg/webcert/notification_sender/notifications/integration/AbstractBaseIT.java, notification-sender/src/test/java/se/inera/intyg/webcert/notification_sender/notifications/integration/RouteIT.java, notification-sender/src/test/java/se/inera/intyg/webcert/notification_sender/notifications/services/v3/NotificationWSClientTest.java, stubs/notification-stub/src/main/java/se/inera/intyg/webcert/notificationstub/NotificationStubRestApi.java, stubs/notification-stub/src/main/java/se/inera/intyg/webcert/notificationstub/v3/CertificateStatusUpdateForCareResponderStub.java, web/src/main/java/se/inera/intyg/webcert/web/service/notification/NotificationServiceImpl.java
Det första försöket hade en misslyckad merge och togs bort (reject) igen. Här kommer en uppstädad PR.
=> INTYGFV-10829: Lagt till inloggad användare till status uppdatering

notification-sender/src/main/java/se/inera/intyg/webcert/notification_sender/notifications/services/v3/NotificationWSClient.java, web/src/main/webapp/version.jsp
Felaktigt mellanslag har dessutom korrigerats i NotificationWSClient...
=> INTYGFV-11896: stängt av sessioner för version.jsp.

notification-sender/src/main/java/se/inera/intyg/webcert/notification_sender/notifications/routes/NotificationRouteHeaders.java, notification-sender/src/main/java/se/inera/intyg/webcert/notification_sender/notifications/services/v3/NotificationInInterceptor.java, notification-sender/src/main/java/se/inera/intyg/webcert/notification_sender/notifications/services/v3/NotificationWSClient.java, notification-sender/src/test/java/se/inera/intyg/webcert/notification_sender/notifications/services/v3/NotificationWSClientTest.java, web/src/main/java/se/inera/intyg/webcert/web/service/notification/NotificationServiceImpl.java
Ett första steg där ett korrelations-id skapas för varje ensklit statusmeddelande har lagts till för att överhuvudtaget kunna avgöra om detta är ett problem eller inte.
=> INTYGFV-11016: Omsändning av notifieringar (activemq) beter sig konstigt

notification-sender/src/main/java/se/inera/intyg/webcert/notification_sender/notifications/routes/NotificationRouteHeaders.java, notification-sender/src/main/java/se/inera/intyg/webcert/notification_sender/notifications/services/v3/NotificationInInterceptor.java, notification-sender/src/main/java/se/inera/intyg/webcert/notification_sender/notifications/services/v3/NotificationWSClient.java, notification-sender/src/test/java/se/inera/intyg/webcert/notification_sender/notifications/services/v3/NotificationWSClientTest.java, web/src/main/java/se/inera/intyg/webcert/web/service/notification/NotificationServiceImpl.java
Denna PR hamnade felaktigt på develop, och är nu cherry-picked till rätt branch.
=> INTYGFV-11016: Omsändning av notifieringar (activemq) beter sig konstigt (#88)

web/src/main/java/se/inera/intyg/webcert/web/bootstrap/UtkastBootstrapBean.java, web/src/main/java/se/inera/intyg/webcert/web/converter/ArendeConverter.java, web/src/main/java/se/inera/intyg/webcert/web/converter/ArendeListItemConverter.java, web/src/main/java/se/inera/intyg/webcert/web/converter/IntygDraftsConverter.java, web/src/main/java/se/inera/intyg/webcert/web/service/arende/ArendeServiceImpl.java, web/src/main/java/se/inera/intyg/webcert/web/service/utkast/UtkastServiceImpl.java, web/src/main/java/se/inera/intyg/webcert/web/web/controller/api/UtkastApiController.java, web/src/main/java/se/inera/intyg/webcert/web/web/controller/api/dto/ArendeListItem.java, web/src/main/java/se/inera/intyg/webcert/web/web/controller/api/dto/ListIntygEntry.java, web/src/main/webapp/app/views/fragorOchSvar/wcEnhetArendenList/wcEnhetArendenList.directive.js, web/src/test/java/se/inera/intyg/webcert/web/service/arende/ArendeServiceTest.java, web/src/test/java/se/inera/intyg/webcert/web/web/controller/api/UtkastApiControllerTest.java
=> INTYGFV-12033: Uppdatera namnet mot hsa för ej hanterande ärende och ej signerade utkast

web/src/main/java/se/inera/intyg/webcert/web/service/diagnos/DiagnosServiceImpl.java
Tagit bort transaktioner för diagnos repot
=> INTYGFV-12752: Removed transactional

web/src/main/java/se/inera/intyg/webcert/web/service/monitoring/MonitoringLogService.java, web/src/main/java/se/inera/intyg/webcert/web/service/monitoring/MonitoringLogServiceImpl.java, web/src/main/java/se/inera/intyg/webcert/web/web/controller/api/JsLogApiController.java, web/src/main/java/se/inera/intyg/webcert/web/web/controller/api/dto/MonitoringRequest.java
Har lagt till ett nytt monitorerings-event för SRS (SRS_MEASURES_DISPLAYED) som skall triggas när användaren scrollat ned till Åtgärder i Stöd för rätt sjukskrivning/SRS-filken.
=> NEW-SRS: Added new monitoring event for SRS (SRS_MEASURES_DISPLAYED)

web/Gruntfile.js, web/bower.json, web/karma.conf.js, web/src/main/webapp/boot-app.jsp, web/src/main/webapp/error.jsp, web/src/main/webapp/new-error.jsp, web/src/main/webapp/pubapp/signapp/index.html, web/src/main/webapp/pubapp/simulator/index.html
Lagt till accessibility-modul för highcharts så att SRS-grafer kan tolkas bättre av skärmläsare
=> INTYGFV-13004: Added accessibility module for Highcharts

web/src/main/java/se/inera/intyg/webcert/web/service/srs/SrsService.java, web/src/main/java/se/inera/intyg/webcert/web/service/srs/SrsServiceImpl.java, web/src/main/java/se/inera/intyg/webcert/web/web/controller/api/SrsApiController.java, web/src/test/java/se/inera/intyg/webcert/web/service/srs/SrsServiceImplTest.java
OBS, infra behöver mergas först: https://github.com/sklintyg/infra/pull/101
* Skapat SrsService och flyttat logik från SrsController
* Lagt till stöd för att dekorera svar med förlängningskedjor
* Enhetstester för SrsService
=> INTYGFV-13170:

web/src/main/java/se/inera/intyg/webcert/web/service/access/CertificateAccessServiceImpl.java, web/src/main/java/se/inera/intyg/webcert/web/service/access/DraftAccessServiceImpl.java, web/src/test/java/se/inera/intyg/webcert/web/service/access/DbCertificateAccessTest.java, web/src/test/java/se/inera/intyg/webcert/web/service/access/DbDraftAccessTest.java, web/src/test/java/se/inera/intyg/webcert/web/service/access/DoiCertificateAccessTest.java, web/src/test/java/se/inera/intyg/webcert/web/service/access/DoiDraftAccessTest.java, web/src/test/java/se/inera/intyg/webcert/web/service/access/Fk7263CertificateAccessTest.java, web/src/test/java/se/inera/intyg/webcert/web/service/access/FkCertificateAccessTest.java, web/src/test/java/se/inera/intyg/webcert/web/service/access/TsCertificateAccessTest.java, web/src/test/java/se/inera/intyg/webcert/web/service/access/TsDraftAccessTest.java
Same rules that apply within av care unit should apply whithin a care provider. NO SJF though! So never allow print between care providers.
=> INTYGFV-12985: Allow printing within the same care provider.

web/src/main/java/se/inera/intyg/webcert/web/web/filter/UnitSelectedAssuranceFilter.java, web/src/main/webapp/WEB-INF/web.xml
Checks if a logged in user has the valdVardenhet property set, else it will send an error response (500) for the request.
=> INTYGFV-12292: Add filter that checks if user has selected a unit

web/src/main/webapp/app/views/fragorOchSvar/enhetArenden.scss, web/src/main/webapp/app/views/fragorOchSvar/wcEnhetArendenList/wcEnhetArendenList.directive.html, web/src/main/webapp/app/views/sokSkrivIntyg/tidigareIntyg.directive.html, web/src/main/webapp/app/views/sokSkrivIntyg/tidigareIntyg.scss
Introduced table break for narrow screen in 'tidigare intyg' and 'ej hanterade arenden' tables . Tables now behave same way as the 'ej signerade utkast' table.
=> INTYGFV-13510: Introduced table break for narrow screens in search and arende screens

build-info.json
Updated to new intygstjanst version in webcert build-info.json
=> INTYGFV-13498: Updated backing service version

notification-sender/src/main/java/se/inera/intyg/webcert/notification_sender/certificatesender/services/CertificateRevokeProcessor.java, notification-sender/src/main/java/se/inera/intyg/webcert/notification_sender/certificatesender/services/CertificateSendProcessor.java, notification-sender/src/main/java/se/inera/intyg/webcert/notification_sender/certificatesender/services/CertificateStoreProcessor.java, notification-sender/src/main/java/se/inera/intyg/webcert/notification_sender/certificatesender/services/RegisterApprovedReceiversProcessor.java, notification-sender/src/main/java/se/inera/intyg/webcert/notification_sender/certificatesender/services/SendMessageToRecipientProcessor.java, notification-sender/src/test/java/se/inera/intyg/webcert/notification_sender/certificatesender/services/CertificateRevokeProcessorTest.java, notification-sender/src/test/java/se/inera/intyg/webcert/notification_sender/certificatesender/services/CertificateSendProcessorTest.java, notification-sender/src/test/java/se/inera/intyg/webcert/notification_sender/certificatesender/services/CertificateStoreProcessorTest.java, notification-sender/src/test/java/se/inera/intyg/webcert/notification_sender/certificatesender/services/RegisterApprovedReceiversProcessorTest.java, notification-sender/src/test/java/se/inera/intyg/webcert/notification_sender/certificatesender/services/SendMessageToRecipientProcessorTest.java
Done according to how I interpreted the jira text under decision. Hope I understood it correctly... (By the way, one of the commit messages accidently got the wrong jira number).
=> INTYGFV-13669: Changed all throws of PermanentException to TemporaryException in certificatesender.services

web/src/main/java/se/inera/intyg/webcert/web/service/facade/CreateCertificateFacadeService.java, web/src/main/java/se/inera/intyg/webcert/web/service/facade/GetCertificateTypesFacadeService.java, web/src/main/java/se/inera/intyg/webcert/web/service/facade/impl/CreateCertificateException.java, web/src/main/java/se/inera/intyg/webcert/web/service/facade/impl/CreateCertificateFacadeServiceImpl.java, web/src/main/java/se/inera/intyg/webcert/web/service/facade/impl/GetCertificateTypesFacadeServiceImpl.java, web/src/main/java/se/inera/intyg/webcert/web/web/controller/facade/CertificateController.java, web/src/main/java/se/inera/intyg/webcert/web/web/controller/facade/CertificateTypeController.java, web/src/main/java/se/inera/intyg/webcert/web/web/controller/facade/dto/CertificateTypeInfoDTO.java, web/src/main/java/se/inera/intyg/webcert/web/web/controller/facade/dto/CreateCertificateResponseDTO.java, web/src/main/java/se/inera/intyg/webcert/web/web/controller/facade/dto/ResourceLinkTypeDTO.java, web/src/main/webapp/WEB-INF/api-cxf-servlet.xml, web/src/test/java/se/inera/intyg/webcert/web/service/facade/impl/CreateCertificateFacadeServiceImplTest.java, web/src/test/java/se/inera/intyg/webcert/web/service/facade/impl/GetCertificateTypesFacadeServiceImplTest.java, web/src/test/java/se/inera/intyg/webcert/web/web/controller/facade/CertificateTypeControllerTest.java
Tests for create certificate service will be added later, when @perfli has the time.
=> INTYGFV-14461: Create new certificate

web/src/main/webapp/app/partials/dbInfo.dialog.html, web/src/main/webapp/app/views/messages.js, web/src/main/webapp/app/views/sokSkrivIntyg/valjUtkastTyp.directive.js
Updated text to new specification.
=> INTYGFV-14011: Updated text.

web/src/main/webapp/app/partials/dbInfo.dialog.html, web/src/main/webapp/app/views/sokSkrivIntyg/valjUtkastTyp.directive.js
Updated to show middle name and format personnr.
=> INTYGFV-14011: Updated to show middle name.

web/src/main/java/se/inera/intyg/webcert/web/service/facade/list/config/GetStaffInfoFacadeServiceImpl.java, web/src/main/java/se/inera/intyg/webcert/web/service/facade/list/config/ListQuestionsConfigFacadeServiceImpl.java, web/src/main/java/se/inera/intyg/webcert/web/service/facade/list/config/factory/ListFilterConfigFactory.java
Added default values for sign to show all if it is an administrator. Also removed administrator as an option in the same dropdown.
=> INTYGFV-14837: Change default value for signed by dropdown

web/src/test/java/se/inera/intyg/webcert/web/service/access/DbDraftAccessTest.java, web/src/test/java/se/inera/intyg/webcert/web/service/access/DoiDraftAccessTest.java, web/src/test/java/se/inera/intyg/webcert/web/service/access/TsDraftAccessTest.java
=> INTYGFV-14815: Updated failing tests.

web/src/main/java/se/inera/intyg/webcert/web/service/facade/impl/certificatefunctions/CertificateSignConfirmationFunctionImpl.java, web/src/main/java/se/inera/intyg/webcert/web/service/utkast/UtkastServiceImpl.java, web/src/test/java/se/inera/intyg/webcert/web/service/facade/impl/certificatefunctions/CertificateSignConfirmationFunctionTest.java
Refactored CertificateSignConfirmationFunctionImpl for better readability.
=> INTYGFV-14931: Added exended functionality to CertificateSignConfirmationFunctionImpl that checks if REPLACED certificates exists for person.

web/src/main/java/se/inera/intyg/webcert/web/service/facade/impl/certificatefunctions/GetCertificatesAvailableFunctionsImpl.java, web/src/test/java/se/inera/intyg/webcert/web/service/facade/impl/GetCertificatesAvailableFunctionsImplTest.java
Tests are also added to verify
=> INTYGFV-14929: Added function sendToDescription that checks the type of certificate and returns the correct description.

web/src/main/java/se/inera/intyg/webcert/web/auth/IdpSelectionFilter.java, web/src/main/java/se/inera/intyg/webcert/web/service/user/dto/WebCertUser.java, web/src/main/java/se/inera/intyg/webcert/web/web/controller/integration/LaunchIntegrationController.java, web/src/main/java/se/inera/intyg/webcert/web/web/controller/legacyintegration/FragaSvarUthoppController.java, web/src/main/resources/application.properties, web/src/main/webapp/WEB-INF/uthopp-integration-cxf-servlet.xml, web/src/test/java/se/inera/intyg/webcert/web/web/controller/integration/CertificateIntegrationControllerTest.java, web/src/test/java/se/inera/intyg/webcert/web/web/controller/integration/LaunchIntegrationControllerTest.java
…quests from rehabstod, and not display error message every time they navigate from rs to wc.
=> INTYGFV-15776: Added new controller to handle launches of webcert from other origins that decorates user with launchFromOrigin attribute.

web/src/main/resources/links/webcert.links.json
Keeping "minaintyg" for backward compatibility.
=> INTYGFV-16134: Update link to intyg

web/src/main/java/se/inera/intyg/webcert/web/auth/common/AuthConstants.java
(cherry picked from commit a612146f6ecc10ebfaed5461b546d9caae5e0665)
=> INTYGFV-16540: Add new auth class for ELEG_AUTH_CLASSES. (#1032)

build.gradle, notification-sender/src/main/java/se/inera/intyg/webcert/notification_sender/notifications/services/NotificationTransformer.java, notification-sender/src/test/java/se/inera/intyg/webcert/notification_sender/notifications/services/NotificationTransformerTest.java, web/src/main/java/se/inera/intyg/webcert/web/csintegration/certificate/CertificateStatusUpdateFactory.java, web/src/main/java/se/inera/intyg/webcert/web/csintegration/certificate/CreateCertificateFromCertificateService.java, web/src/main/java/se/inera/intyg/webcert/web/csintegration/certificate/CreateDraftCertificateFromCS.java, web/src/main/java/se/inera/intyg/webcert/web/csintegration/certificate/DeleteCertificateFromCertificateService.java, web/src/main/java/se/inera/intyg/webcert/web/csintegration/certificate/FinalizeCertificateSignService.java, web/src/main/java/se/inera/intyg/webcert/web/csintegration/certificate/NotificationMessageFactory.java, web/src/main/java/se/inera/intyg/webcert/web/csintegration/certificate/NotificationMessageMapper.java, web/src/main/java/se/inera/intyg/webcert/web/csintegration/certificate/PublishCertificateStatusUpdateService.java, web/src/main/java/se/inera/intyg/webcert/web/csintegration/certificate/RevokeCertificateFromCertificateService.java, web/src/main/java/se/inera/intyg/webcert/web/csintegration/certificate/SaveCertificateInCertificateService.java, web/src/main/java/se/inera/intyg/webcert/web/csintegration/certificate/SendCertificateFromCertificateService.java, web/src/main/java/se/inera/intyg/webcert/web/csintegration/integration/CSIntegrationRequestFactory.java, web/src/main/java/se/inera/intyg/webcert/web/service/notification/NotificationService.java, web/src/main/java/se/inera/intyg/webcert/web/service/notification/NotificationServiceImpl.java, web/src/test/java/se/inera/intyg/webcert/web/csintegration/certificate/CreateCertificateFromCertificateServiceTest.java, web/src/test/java/se/inera/intyg/webcert/web/csintegration/certificate/CreateDraftCertificateFromCSTest.java, web/src/test/java/se/inera/intyg/webcert/web/csintegration/certificate/DeleteCertificateFromCertificateServiceTest.java, web/src/test/java/se/inera/intyg/webcert/web/csintegration/certificate/FinalizeCertificateSignServiceTest.java, web/src/test/java/se/inera/intyg/webcert/web/csintegration/certificate/NotificationMessageFactoryTest.java, web/src/test/java/se/inera/intyg/webcert/web/csintegration/certificate/NotificationMessageMapperTest.java, web/src/test/java/se/inera/intyg/webcert/web/csintegration/certificate/PublishCertificateStatusUpdateServiceTest.java, web/src/test/java/se/inera/intyg/webcert/web/csintegration/certificate/RevokeCertificateFromCertificateServiceTest.java, web/src/test/java/se/inera/intyg/webcert/web/csintegration/certificate/SaveCertificateInCertificateServiceTest.java, web/src/test/java/se/inera/intyg/webcert/web/csintegration/certificate/SendCertificateFromCertificateServiceTest.java, web/src/test/java/se/inera/intyg/webcert/web/csintegration/integration/CSIntegrationRequestFactoryTest.java
=> INTYGFV-16539: Implemented PublishCertificateStatusUpdateService that handles publication of CertificateStatusUpdateForCareType.

web/src/main/java/se/inera/intyg/webcert/web/csintegration/integration/ListIntygEntryConverter.java, web/src/main/java/se/inera/intyg/webcert/web/service/facade/impl/certificatefunctions/CertificateRenewFunction.java, web/src/main/java/se/inera/intyg/webcert/web/service/facade/list/ResourceLinkListHelperImpl.java, web/src/main/java/se/inera/intyg/webcert/web/web/util/resourcelinks/dto/ActionLinkType.java, web/src/test/java/se/inera/intyg/webcert/web/csintegration/integration/ListIntygEntryConverterTest.java, web/src/test/java/se/inera/intyg/webcert/web/service/facade/impl/list/ResourceLinkListHelperImplTest.java
=> INTYGFV-16653: Added mapping for RENEW_CERTIFICATE in listview.

web/src/main/java/se/inera/intyg/webcert/web/service/facade/list/config/dto/ListFilterDateConfig.java, web/src/main/java/se/inera/intyg/webcert/web/service/facade/list/config/factory/ListFilterConfigFactory.java, web/src/test/java/se/inera/intyg/webcert/web/service/facade/impl/list/ListDraftsConfigFacadeServiceImplTest.java, web/src/test/java/se/inera/intyg/webcert/web/service/facade/impl/list/ListQuestionsConfigFacadeServiceImplTest.java
When getting drafts and questions we want to set a default from date to 3 months form today.
=> K1J-528: Add a default from date
